### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kakeru-takakusaki** [kakeru-takakusaki/furima-34512#9]
# URL
https://furima-34512.herokuapp.com/
# Basic認証
ID
admin
パスワード
2222
# ユーザー 1
メールアドレス
test@test
パスワード
test1234
# ユーザー 2
メールアドレス
sample@sample
パスワード
sample1234

**Comment by runak25033** [comment]
ご提出ありがとうございました。

問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
<img width="916" alt="最終課題LGTM2" src="https://user-images.githubusercontent.com/79125420/110875128-66ad0180-8318-11eb-8ddb-a5d530c02165.png">
